"""
Projection module — computes t-SNE 2D from k-dimensional embeddings.

Full-dataset 2D projections are loaded from the pre-computed parquet
(``embedded_songs_2d.parquet``, generated by ``data_pipeline.py``). The
API never recomputes the full-dataset projection on the fly — if the
parquet is missing the response is empty and the user must run the
pipeline. Filtered subsets do recompute t-SNE on the surviving songs.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
from sklearn.manifold import MDS, TSNE

from app.backend.core.data_loader import load_visible_songs
from app.backend.core.similarity import cosine_matrix

logger = logging.getLogger(__name__)

_DATA_DIR = Path(__file__).parent.parent / "data"
_PROCESSED_DIR = _DATA_DIR / "processed"
_PRECOMP_2D = _PROCESSED_DIR / "embedded_songs_2d.parquet"

# Cache for full-dataset 2D points (computed once, reused on reset).
_cached_all_2d: list[dict] | None = None


def _songs_to_matrix(songs: list[dict]) -> np.ndarray:
    """Extract the k-dim embedding from each song into an (n, k) array."""
    return np.array([s["embedding"] for s in songs], dtype=np.float64)


def _build_points(songs: list[dict], coords: np.ndarray) -> list[dict]:
    """Combine song metadata with 2D coordinates."""
    return [
        {
            "id":     s["id"],
            "x":      round(float(coords[i, 0]), 4),
            "y":      round(float(coords[i, 1]), 4),
            "title":  s["title"],
            "artist": s["artist"],
            "genre":  s["genre"],
            "role":   s.get("role", "neighbor"),
        }
        for i, s in enumerate(songs)
    ]


def compute_tsne_2d(songs: list[dict]) -> list[dict]:
    """t-SNE 2D over the (typically small) survivor set."""
    if not songs:
        return []
    matrix = _songs_to_matrix(songs)
    n = matrix.shape[0]
    if n <= 1:
        return _build_points(songs, np.zeros((n, 2)))

    perplexity = max(1, min(30, n - 1))
    init = "pca" if n >= 2 else "random"
    coords = TSNE(
        n_components=2,
        perplexity=perplexity,
        random_state=42,
        init=init,
        max_iter=500,
    ).fit_transform(matrix)
    return _build_points(songs, coords)


def _load_precomputed_2d() -> list[dict]:
    """
    Load 2D positions from the parquet, but only for songs that survived
    ``select_top_songs`` (see data_loader.load_visible_songs). Keeps the
    point cloud and the song list perfectly in sync.
    """
    import pyarrow.parquet as pq

    df = pq.read_table(_PRECOMP_2D, columns=["id_lyrics", "x", "y"]).to_pandas()
    id_to_song = {s["id"]: s for s in load_visible_songs()}  # already capped

    points: list[dict] = []
    for _, row in df.iterrows():
        sid = int(row["id_lyrics"])
        song = id_to_song.get(sid)
        if song is None:
            continue  # filtered out by select_top_songs
        points.append({
            "id":     sid,
            "x":      round(float(row["x"]), 4),
            "y":      round(float(row["y"]), 4),
            "title":  song["title"],
            "artist": song["artist"],
            "genre":  song["genre"],
            "role":   "neighbor",
        })
    return points


def get_all_projections_2d() -> list[dict]:
    """Cached 2D projections for the visible songs."""
    global _cached_all_2d
    if _cached_all_2d is None:
        if not _PRECOMP_2D.exists():
            logger.warning(
                "No 2D parquet at %s. Run `python -m data_pipeline.execute_all` "
                "or start the API with RECOMPUTE_2D=1.",
                _PRECOMP_2D,
            )
            _cached_all_2d = []
        else:
            try:
                _cached_all_2d = _load_precomputed_2d()
                logger.info("Loaded %d pre-computed 2D projections", len(_cached_all_2d))
            except Exception as exc:
                logger.error("Could not load 2D parquet (%s)", exc)
                _cached_all_2d = []
    return _cached_all_2d


def get_visible_song_ids() -> set[int]:
    """IDs of every song that currently has a 2D projection."""
    return {p["id"] for p in get_all_projections_2d()}


def compute_neighborhood_2d(
    songs: list[dict],
    focal_id: int,
    previous_song_id: int | None = None,
    previous_positions: dict[int, tuple[float, float]] | None = None,
) -> list[dict]:
    """
    2D layout for a neighborhood via metric MDS on cosine distances.

    The focal song is placed at the origin. If ``previous_positions`` are
    given the layout is rotated (Procrustes) and overlap songs are snapped
    to their old positions, so visual continuity is preserved across hops.
    """
    if not songs:
        return []

    n = len(songs)
    if n == 1:
        return _build_points(songs, np.zeros((1, 2)))

    matrix = _songs_to_matrix(songs)
    dist_mat = (1.0 - cosine_matrix(matrix)).astype(np.float64)
    np.fill_diagonal(dist_mat, 0.0)

    n_init = 4 if n <= 30 else 1
    coords = MDS(
        n_components=2,
        metric_mds=True,
        metric="precomputed",
        init="random",
        random_state=42,
        n_init=n_init,
        normalized_stress=False,
        max_iter=300,
    ).fit_transform(dist_mat)

    focal_idx = next((i for i, s in enumerate(songs) if s["id"] == focal_id), 0)
    coords = coords - coords[focal_idx]

    non_focal_mask = np.ones(n, dtype=bool)
    non_focal_mask[focal_idx] = False
    if non_focal_mask.any():
        dists = np.linalg.norm(coords[non_focal_mask], axis=1)
        p75 = float(np.percentile(dists, 75))
        if p75 > 1e-8:
            coords = coords / p75

    if previous_positions and focal_id in previous_positions:
        fx_old, fy_old = previous_positions[focal_id]
        A_rows: list[list[float]] = []
        B_rows: list[list[float]] = []
        overlap: list[tuple[int, float, float]] = []
        for i, song in enumerate(songs):
            sid = song["id"]
            if sid == focal_id or sid not in previous_positions:
                continue
            px_old, py_old = previous_positions[sid]
            bx, by = px_old - fx_old, py_old - fy_old
            A_rows.append(coords[i].tolist())
            B_rows.append([bx, by])
            overlap.append((i, bx, by))

        if A_rows:
            A = np.array(A_rows, dtype=np.float64)
            B = np.array(B_rows, dtype=np.float64)
            U, _s, Vt = np.linalg.svd(A.T @ B)
            R = U @ Vt
            if np.linalg.det(R) < 0:
                U[:, -1] *= -1
                R = U @ Vt
            coords = coords @ R
            for idx, bx, by in overlap:
                coords[idx, 0] = bx
                coords[idx, 1] = by

    return _build_points(songs, coords)


def invalidate_cache() -> None:
    """Clear the 2D cache (e.g. after regenerating the parquet)."""
    global _cached_all_2d
    _cached_all_2d = None
