"""
Build ``app/backend/data/artist_genres.csv`` from a manually curated dict.

The dict ``ARTIST_GENRES`` below contains one entry per unique artist in
``top_5000_songs.csv``. Labels were assigned by Claude Opus 4.7 using
knowledge of the Catalan music scene + song-title heuristics for unfamiliar
artists. ``confidence`` is the labeler's own subjective rating:

* ``high``   — well-known artist; primary style is clear.
* ``medium`` — inferred from song titles (e.g. "Jota" / "Bolero" → folk,
                multiple "Cançó de bressol" → infantil) with reasonable
                confidence.
* ``low``    — guess based on weak signals; the user may want to review.

The 11-label taxonomy is intentionally narrow:
    pop, rock, indie, folk, rumba, ska, punk, hip-hop,
    electronica, havaneres, infantil

Conventions:
* ``ska`` covers ska, reggae, and the Catalan "mestizo / patxanga" wave
  (Txarango, La Pegatina, Buhos, Doctor Prats).
* ``folk`` covers cantautor / Nova Cançó / traditional / sardanes / choral.
* ``indie`` covers indie-pop and alternative-pop that doesn't fit ``rock``.
* ``rumba`` covers rumba catalana and the modern "nova rumba" wave
  (The Tyets, Figa Flawas).
* ``electronica`` covers club / synth / EDM / electronic-dancehall.

Usage:
    python -m etl.build_artist_genres            # writes artist_genres.csv
    python -m etl.build_artist_genres --check    # just validate coverage
"""

from __future__ import annotations

import argparse
import csv
import logging
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

_REPO_ROOT     = Path(__file__).resolve().parent.parent
_TOP_5000_CSV  = _REPO_ROOT / "app" / "backend" / "data" / "top_5000_songs.csv"
_OUTPUT_CSV    = _REPO_ROOT / "app" / "backend" / "data" / "artist_genres.csv"

GENRES = (
    "pop", "rock", "indie", "folk", "rumba", "ska", "punk",
    "hip-hop", "electronica", "havaneres", "infantil",
)

# (genre, confidence)
ARTIST_GENRES: dict[str, tuple[str, str]] = {
    # ── Tier A — well-known artists (high confidence) ─────────────────────
    "Lluís Llach":                    ("folk",     "high"),
    "Club Súper 3":                   ("infantil", "high"),
    "La Trinca":                      ("pop",      "high"),
    "Txarango":                       ("ska",      "high"),
    "Joan Manuel Serrat":             ("folk",     "high"),
    "Maria del Mar Bonet":            ("folk",     "high"),
    "Dàmaris Gelabert":               ("infantil", "high"),
    "La Ludwig Band":                 ("pop",      "high"),
    "Els Amics de les Arts":          ("indie",    "high"),
    "Els Pets":                       ("rock",     "high"),
    "Raimon":                         ("folk",     "high"),
    "Manel":                          ("indie",    "high"),
    "Antònia Font":                   ("indie",    "high"),
    "Oques Grasses":                  ("indie",    "high"),
    "Xesco Boix":                     ("infantil", "high"),
    "Ovidi Montllor":                 ("folk",     "high"),
    "Marina Rossell":                 ("folk",     "high"),
    "Núria Feliu":                    ("pop",      "high"),
    "Dani Miquel":                    ("infantil", "high"),
    "Esquirols":                      ("folk",     "high"),
    "La Gossa Sorda":                 ("ska",      "high"),
    "Música Nostra":                  ("folk",     "high"),
    "Ginestà":                        ("indie",    "high"),
    "La Fúmiga":                      ("pop",      "high"),
    "Pau Riba":                       ("rock",     "high"),
    "Xiula":                          ("infantil", "high"),
    "Pep Gimeno 'Botifarra'":         ("folk",     "high"),
    "Els Catarres":                   ("pop",      "high"),
    "Obrint Pas":                     ("ska",      "high"),
    "Port Bo":                        ("havaneres","high"),
    "Al Tall":                        ("folk",     "high"),
    "Paco Muñoz":                     ("folk",     "high"),
    "Pau Vallvé":                     ("indie",    "high"),
    "Sopa de Cabra":                  ("rock",     "high"),
    "Tomeu Penya":                    ("folk",     "high"),
    "Jaume Arnella":                  ("folk",     "high"),
    "Ara va de bo":                   ("infantil", "medium"),
    "Zoo":                            ("ska",      "high"),
    "Guillermina Motta":              ("pop",      "high"),
    "Josep Maria Espinàs, Francesc Burrull": ("infantil", "high"),
    "Al·lèrgiques al pol·len":        ("indie",    "medium"),
    "Lax'n'Busto":                    ("rock",     "high"),
    "Grup de Folk":                   ("folk",     "high"),
    "Ferran Palau":                   ("indie",    "high"),
    "Toni Giménez":                   ("infantil", "high"),
    "Joan Dausà":                     ("pop",      "high"),
    "Uc":                             ("folk",     "high"),
    "Mishima":                        ("indie",    "high"),
    "El Pont d'Arcalís":              ("folk",     "high"),
    "Buhos":                          ("ska",      "high"),
    "Mainasons":                      ("infantil", "high"),
    "Auxili":                         ("ska",      "high"),
    "Blaumut":                        ("indie",    "high"),
    "The Penguins":                   ("infantil", "medium"),
    "Maria Jaume":                    ("indie",    "high"),
    "Brams":                          ("punk",     "high"),
    "The Tyets":                      ("rumba",    "high"),
    "Mama Dousha":                    ("hip-hop",  "high"),
    "31 FAM":                         ("hip-hop",  "high"),
    "Naina":                          ("indie",    "high"),
    "La Pataqueta":                   ("infantil", "high"),
    "Cucorba":                        ("infantil", "high"),
    "Sau":                            ("rock",     "high"),
    "El Pony Pisador":                ("folk",     "high"),
    "Dagoll Dagom":                   ("folk",     "medium"),
    "Ramon Muntaner":                 ("folk",     "high"),
    "Figa Flawas":                    ("rumba",    "high"),
    "Alosa":                          ("folk",     "high"),
    "Xarim Aresté":                   ("indie",    "high"),
    "Crim":                           ("punk",     "high"),
    "Roger Mas":                      ("folk",     "high"),
    "Sexenni":                        ("indie",    "high"),
    "El Diluvi":                      ("ska",      "high"),
    "Adrià Puntí":                    ("rock",     "high"),
    "Macedònia":                      ("infantil", "high"),
    "Judit Neddermann":               ("folk",     "high"),
    "Anna Andreu":                    ("folk",     "medium"),
    "Mar Pujol":                      ("folk",     "medium"),
    "La Maria":                       ("indie",    "medium"),
    "Quimi Portet":                   ("rock",     "high"),
    "Aspencat":                       ("ska",      "high"),
    "Emili Vendrell":                 ("folk",     "high"),
    "Adala":                          ("ska",      "high"),
    "Doctor Prats":                   ("ska",      "high"),
    "Dan Peralbo i El Comboi":        ("pop",      "medium"),
    "Alimara":                        ("folk",     "medium"),
    "La Bressola – Escoles Catalanes":("infantil", "high"),
    "Albert Pla":                     ("folk",     "high"),
    "Ramon Calduch":                  ("folk",     "high"),
    "Jordi Barre":                    ("folk",     "high"),
    "Sisa":                           ("folk",     "high"),
    "Pau Riba, Orchestra Fireluche":  ("rock",     "high"),
    "Companyia El Petit Príncep":     ("infantil", "high"),
    "Carles Caselles":                ("rock",     "medium"),
    "enMatu":                         ("indie",    "medium"),
    "Obeses":                         ("rock",     "high"),
    "Gossos":                         ("rock",     "high"),
    "Orxata":                         ("ska",      "high"),
    "Toti Soler":                     ("folk",     "high"),
    "Umpah-Pah":                      ("rock",     "high"),
    "Xavier Ribalta":                 ("folk",     "high"),
    "Judit Neddermann, Pau Figueres": ("folk",     "high"),
    "Remigi Palmero":                 ("folk",     "high"),
    "Pep Puigdemont":                 ("infantil", "high"),
    "El Petit de Cal Eril":           ("indie",    "high"),
    "Magalí Sare":                    ("folk",     "high"),
    "Pep Picas":                      ("folk",     "medium"),
    "Romàntic Dimoni":                ("rock",     "medium"),
    "Mazoni":                         ("indie",    "high"),
    "Borja Penalba, Mireia Vives":    ("folk",     "high"),
    "Maria Arnal i Marcel Bagés":     ("folk",     "high"),
    "Falsterbo 3":                    ("folk",     "high"),
    "Rudymentari":                    ("indie",    "medium"),
    "Els miralls de Dylan":           ("folk",     "high"),
    "Salomé":                         ("folk",     "medium"),
    "Sva-ters":                       ("punk",     "medium"),
    "Biel Majoral":                   ("folk",     "high"),
    "The Companys":                   ("rock",     "high"),
    "Marala":                         ("folk",     "high"),
    "La Principal de la Bisbal, Polifònica de Puig-Reig": ("folk", "high"),
    "Toti Soler, Cinta Massip":       ("folk",     "high"),
    "Abril":                          ("indie",    "medium"),
    "Follim Follam":                  ("folk",     "high"),
    "Teresa Rebull":                  ("folk",     "high"),
    "Quico Pi de la Serra":           ("folk",     "high"),
    "Ven'nus":                        ("indie",    "medium"),
    "Joan-Pau Giné":                  ("folk",     "high"),
    "Xavi Lloses":                    ("folk",     "medium"),
    "Ressonadors":                    ("folk",     "high"),
    "Els Pescadors de L'Escala":      ("havaneres","high"),
    "Bons nois":                      ("indie",    "medium"),
    "Anna Llopart i Xavi G. Cabré":   ("infantil", "medium"),
    "Xavi Sarrià":                    ("ska",      "high"),
    "Baya Baye MGT Los Sosis":        ("hip-hop",  "medium"),
    "Quico el Célio, el Noi i el Mut de Ferreries, Pep Gimeno 'Botifarra'": ("folk", "high"),
    "Rah-mon Roma":                   ("infantil", "high"),
    "Quico el Célio, el Noi i el Mut de Ferreries": ("folk", "high"),
    "S'Albaida":                      ("folk",     "medium"),
    "Josep Maria Espinàs":            ("folk",     "high"),
    "Remei de Ca la Fresca":          ("punk",     "high"),
    "Jo Jet i Maria Ribot":           ("folk",     "high"),
    "Roba Estesa":                    ("folk",     "high"),
    "Esplai Sant Llorenç":            ("infantil", "medium"),
    "Feliu Ventura":                  ("folk",     "high"),
    "Gertrudis":                      ("rumba",    "high"),
    "Smoking Souls":                  ("indie",    "high"),
    "Socunbohemio":                   ("folk",     "medium"),
    "Joan Isaac":                     ("folk",     "high"),
    "La Trinca, Guillermina Motta":   ("pop",      "high"),
    "Torrat i Bullit":                ("folk",     "medium"),
    "Petit Taller de Cançons":        ("infantil", "high"),
    "Pilseners":                      ("punk",     "medium"),
    "gavina.mp3":                     ("indie",    "medium"),
    "Baya Baye MGT Los Sosis, Viktor Pizza": ("hip-hop", "medium"),
    "Ambauka":                        ("infantil", "high"),
    "P.A.W.N. Gang":                  ("hip-hop",  "high"),
    "Manu Guix":                      ("pop",      "high"),
    "JULS":                           ("folk",     "medium"),
    "Groggy Rude":                    ("ska",      "medium"),
    "Pep Gimeno 'Botifarra', La Rondalla U.M. la Nucia": ("folk", "high"),
    "Germà Negre":                    ("folk",     "high"),
    "Pau Alabajos":                   ("folk",     "high"),
    "Ja t'ho diré":                   ("pop",      "high"),
    "El Pot Petit":                   ("infantil", "high"),
    "Sergi Dantí":                    ("folk",     "medium"),
    "Miki Núñez":                     ("pop",      "high"),
    "Traginada":                      ("folk",     "medium"),
    "Franca Masu":                    ("folk",     "high"),
    "Nou Romancer":                   ("folk",     "medium"),
    "Maria Laffitte":                 ("folk",     "high"),
    "Els Atrapasomnis":               ("infantil", "high"),
    "Miquel Pujadó":                  ("folk",     "high"),
    "Lluís el Sifoner":               ("folk",     "high"),
    "Skatalà":                        ("ska",      "high"),
    "Bon Vent!":                      ("folk",     "medium"),
    "Cactus":                         ("indie",    "medium"),
    "Josep Carreras":                 ("pop",      "high"),
    "Beth":                           ("pop",      "high"),
    "Sandra Monfort":                 ("indie",    "high"),
    "Cris Juanico":                   ("folk",     "high"),
    "Ossifar":                        ("rock",     "high"),
    "Strombers":                      ("ska",      "high"),
    "Joan Miquel Oliver":             ("indie",    "high"),
    "Ernest Prana":                   ("indie",    "medium"),
    "Àlex Pérez":                     ("pop",      "medium"),
    "Guillem Gisbert":                ("indie",    "high"),
    "Sis Som":                        ("folk",     "high"),
    "Svetlana":                       ("indie",    "medium"),
    "Anna d'Ivori":                   ("indie",    "medium"),
    "Xaloc Música":                   ("folk",     "high"),
    "Guillem d'Efak":                 ("folk",     "high"),
    "Malifeta":                       ("punk",     "medium"),
    "Arnau Tordera, Secretariat de Corals Infantils de Catalunya": ("infantil", "high"),
    "Jordi Tonietti":                 ("infantil", "medium"),
    "The Demencials":                 ("rock",     "medium"),
    "Enyor":                          ("indie",    "medium"),
    "Anna Ferrer":                    ("folk",     "high"),
    "At Versaris":                    ("hip-hop",  "high"),
    "Jonatan Penalba":                ("folk",     "medium"),
    "Roslyn":                         ("folk",     "medium"),
    "Stay Homas":                     ("pop",      "high"),
    "Minibús Intergalàctic":          ("indie",    "medium"),
    "Aina Palmer":                    ("indie",    "medium"),
    "Celdoni Fonoll":                 ("folk",     "high"),
    "Queta & Teo":                    ("infantil", "high"),
    "Companyia Elèctrica Dharma":     ("rock",     "high"),
    "La Pegatina":                    ("ska",      "high"),
    "Flashy Ice Cream":               ("hip-hop",  "high"),
    "Carles Dénia":                   ("folk",     "high"),
    "Inadaptats":                     ("punk",     "high"),
    "La Troba Kung-Fú":               ("ska",      "high"),
    "Rafael Subirachs":                ("folk",    "high"),
    "Trinxats":                       ("indie",    "medium"),
    "Triquell":                       ("hip-hop",  "high"),
    "Lali BeGood":                    ("infantil", "high"),
    "La Clika":                       ("infantil", "medium"),
    "Família Picarol":                ("infantil", "medium"),
    "Lildami":                        ("hip-hop",  "high"),
    "Falsterbo Marí":                 ("folk",     "high"),
    "FADES":                          ("hip-hop",  "medium"),
    "Urbàlia Rurana":                 ("folk",     "high"),
    "Extraño Weys":                   ("indie",    "low"),
    "Jaume Arnella, Ferran Martínez": ("folk",     "high"),
    "Surti Com Surti":                ("folk",     "medium"),
    "Júlia Colom":                    ("indie",    "high"),
    "Julieta":                        ("pop",      "high"),
    "Pere Tàpias":                    ("folk",     "high"),
    "Xanguito":                       ("pop",      "high"),
    "Els Valldemossa":                ("folk",     "high"),
    "Mariona Escoda":                 ("indie",    "medium"),
    "Sangtraït":                      ("rock",     "high"),
    "Quinto":                         ("hip-hop",  "high"),
    "Xerramequ Tiquis Miquis, Núria Lozano": ("folk", "medium"),
    "Al Tall, Maria del Mar Bonet":   ("folk",     "high"),
    "Filferro":                       ("pop",      "medium"),
    "Nina, Port Bo":                  ("havaneres","high"),
    "Ai, Ai, Ai":                     ("folk",     "low"),
    "Sisa, Dagoll Dagom":             ("folk",     "high"),
    "Gemma Humet":                    ("folk",     "high"),
    "Gerard Quintana":                ("rock",     "high"),
    "Miquel Serra":                   ("indie",    "high"),
    "Xitxarel·los":                   ("folk",     "high"),
    "Esther":                         ("pop",      "low"),
    "Al-Mayurqa":                     ("folk",     "medium"),
    "Ignasi Roda":                    ("folk",     "medium"),
    "Mesclat":                        ("folk",     "medium"),
    "Grup Portitxol Xàbia":           ("folk",     "high"),
    "Alfred García":                  ("pop",      "high"),
    "Saïm":                           ("indie",    "low"),
    "TESA":                           ("ska",      "low"),
    "Peret":                          ("rumba",    "high"),
    "Pèl de Gall":                    ("indie",    "low"),
    "KOP":                            ("punk",     "high"),
    "De Paper":                       ("infantil", "high"),
    "Borja Penalba":                  ("folk",     "high"),
    "J.M. Baule":                     ("folk",     "low"),
    "Cala Vento":                     ("indie",    "high"),
    "Càlic":                          ("folk",     "medium"),
    "Mak & Sak feat. Xana":           ("pop",      "low"),
    "The Binigaus Band":              ("folk",     "medium"),
    "Roger Padrós":                   ("pop",      "medium"),
    "Peix Fregit, Port Bo":           ("havaneres","high"),
    "Dani6ix & Kashlo":               ("hip-hop",  "high"),
    "La Carxofa i la Ceba amb en Victu Allioli": ("infantil", "high"),
    "S'Estol des Gerricó":            ("folk",     "medium"),
    "Sílvia Pérez Cruz":              ("folk",     "high"),
    "Maria del Mar Bonet, Borja Penalba": ("folk",  "high"),
    "Cesk Freixas":                   ("folk",     "high"),
    "La Tresca i la Verdesca":        ("infantil", "high"),
    "Toni Xuclà":                     ("folk",     "high"),
    "Refree, Sílvia Pérez Cruz":      ("folk",     "high"),
    "Pastorets Rock":                 ("rock",     "high"),
    "Projecte Mut":                   ("folk",     "low"),
    "Gemma Abrié":                    ("indie",    "medium"),
    "Gato Pérez":                     ("rumba",    "high"),
    "Quart creixent":                 ("folk",     "medium"),
    "2princesesbarbudes":             ("infantil", "high"),
    "Posidònia":                      ("folk",     "medium"),
    "Ramonets":                       ("infantil", "medium"),
    "La Iaia":                        ("indie",    "medium"),
    "Quercus":                        ("folk",     "low"),
    "Mushkaa":                        ("pop",      "high"),
    "Opció k-95":                     ("punk",     "high"),
    "La Xica":                        ("indie",    "low"),
    "Sabor de Gràcia":                ("rumba",    "high"),
    "Kitsch":                         ("indie",    "low"),
    "Joan Josep Mayans":              ("folk",     "medium"),
    "Humus":                          ("folk",     "low"),
    "Ovidi4":                         ("folk",     "high"),
    "Salvador Escamilla":             ("pop",      "high"),
    "Maria del Carme Girau":          ("folk",     "low"),
    "Maria Hein":                     ("indie",    "high"),
    "Rumbalbar":                      ("rumba",    "medium"),
    "Joan Garriga i el Mariatxi galàctic": ("ska",  "high"),
    "Maria Consol Casajoana, Ramon Casajoana": ("folk", "medium"),
    "Marc Parrot":                    ("infantil", "high"),
    "Renaldo & Clara":                ("indie",    "high"),
    "Rovell d'ou":                    ("infantil", "high"),
    "Pau i Jordi":                    ("folk",     "medium"),
    "Grimpallunes":                   ("infantil", "medium"),
    "Sara Roy":                       ("indie",    "medium"),
    "Lídia Pujol":                    ("folk",     "high"),
    "Miquel Abras":                   ("pop",      "medium"),
    "Pepet i Marieta":                ("ska",      "high"),
    "Los Manolos":                    ("rumba",    "high"),
    "Francesc Ribera Titot":          ("folk",     "high"),
    "Nina":                           ("pop",      "high"),
    "Siderland":                      ("indie",    "low"),
    "Tralla":                         ("folk",     "low"),
    "Bajoqueta Rock":                 ("rock",     "high"),
    "Celobert":                       ("indie",    "low"),
    "Toti Soler, Ester Formosa":      ("folk",     "high"),
    "Es Revetlers":                   ("folk",     "medium"),
    "Clara":                          ("folk",     "low"),
    "Com sona?":                      ("infantil", "medium"),
    "Sidonie":                        ("indie",    "high"),
    "Tornaveus":                      ("folk",     "medium"),
    "Corrandes Animació":             ("infantil", "high"),
    "Els Groullers":                  ("folk",     "medium"),
    "Coses":                          ("folk",     "medium"),
    "Cris Juanico, Original Jazz Orquestra Taller de Músics": ("folk", "high"),
    "Suu":                            ("pop",      "high"),
    "Whiskyn's":                      ("rock",     "high"),
    "El Sac de Cançons":              ("folk",     "medium"),
    "Xató":                           ("folk",     "low"),
    "Anegats":                        ("indie",    "low"),
    "Dijous Paella":                  ("pop",      "low"),
    "El Corral de Pepeta":            ("folk",     "low"),
    "Andreu Valor":                   ("folk",     "high"),
    "Tarta Relena":                   ("folk",     "high"),
    "Dyango":                         ("pop",      "high"),
    "Ebri Knight":                    ("folk",     "high"),
    "Esclafits i castanyetes":        ("folk",     "high"),
    "Terratombats":                   ("ska",      "high"),
    "Vidres a la sang":               ("indie",    "low"),
    "Fetus":                          ("rock",     "medium"),
    "Banda Neon":                     ("pop",      "low"),
    "Carles Belda":                   ("folk",     "high"),
    "Canimas":                        ("indie",    "low"),
    "Ceaxe":                          ("indie",    "low"),
    "República Ska":                  ("ska",      "high"),
    "Júlia Moumen":                   ("indie",    "low"),
    "Lágrimas de Sangre":             ("hip-hop",  "high"),
    "De Gairó":                       ("indie",    "low"),
    "Anna Roig i l'Ombre de Ton Chien":("folk",    "high"),
    "Pastora":                        ("pop",      "medium"),
    "Kelly Isaiah":                   ("hip-hop",  "medium"),
    "Pep de la Tona":                 ("folk",     "low"),
    "David Ros":                      ("indie",    "low"),
    "VerdCel":                        ("folk",     "medium"),
    "L'Eriçó Punxegut":               ("infantil", "medium"),
    "Rauxa":                          ("folk",     "low"),
    "Animal":                         ("rock",     "low"),
    "Bèrnia":                         ("indie",    "low"),
    "Diana Murr":                     ("indie",    "low"),
    "Mari Dolç":                      ("infantil", "low"),
    "Riu":                            ("folk",     "low"),
    "Pere Figueres":                  ("folk",     "high"),
    "Lou":                            ("pop",      "low"),
    "The New Catalan Ensemble":       ("folk",     "medium"),
    "Andreu Rifé":                    ("indie",    "low"),
    "Pablo Alborán":                  ("pop",      "high"),
    "Pitxorines":                     ("folk",     "medium"),
    "Dorigen":                        ("indie",    "low"),
    "Josep Tero":                     ("folk",     "high"),
    "Dr. Calypso":                    ("ska",      "high"),
    "Ultramar":                       ("folk",     "low"),
    "Josep Guardiola":                ("pop",      "high"),
    "Lo Pau de Ponts":                ("folk",     "high"),
    "Llengua Morta":                  ("indie",    "low"),
    "La Carrau":                      ("folk",     "high"),
    "La Bicicleta":                   ("folk",     "low"),
    "Arrap":                          ("indie",    "low"),
    "Tremendu":                       ("indie",    "low"),
    "Balma":                          ("indie",    "low"),
    "Bars":                           ("indie",    "low"),
    "Maldol":                         ("indie",    "low"),
    "La Publicitat":                  ("indie",    "low"),
    "Clara Peya":                     ("folk",     "high"),
    "Cap quadrat":                    ("indie",    "low"),
    "La Portàtil FM":                 ("folk",     "medium"),
    "La Porta dels Somnis":           ("pop",      "low"),
    "Cap Pela":                       ("folk",     "high"),
    "La Murga":                       ("infantil", "low"),
    "Au d'Astí!":                     ("folk",     "low"),
    "Cookah P, Sula, Shala Beatz":    ("hip-hop",  "medium"),
    "At Versaris, Asstrio":           ("hip-hop",  "high"),
    "Tomàs de los Santos":            ("folk",     "medium"),
    "La Garota d'Empordà":            ("folk",     "low"),
    "Teràpia de Shock":               ("punk",     "low"),
    "Artur Àlvarez":                  ("folk",     "low"),
    "Cor Madrigal":                   ("folk",     "medium"),
    "Tiu":                            ("indie",    "low"),
    "Trobadorets":                    ("infantil", "medium"),
    "Big Mama":                       ("pop",      "high"),
    "Arribar i ploure":               ("indie",    "low"),
    "Raixa tradicional":              ("folk",     "high"),
    "Pep Sala":                       ("rock",     "high"),
    "La Cobleta de la Selva":         ("folk",     "high"),
    "Pau Riba, Big ensemble Taller de Músics": ("rock", "high"),
    "Pomada":                         ("indie",    "low"),
    "Marc Vilajuana":                 ("indie",    "low"),
    "Arturo Gaya":                    ("folk",     "medium"),
    "Xavi Túrnez, Sesé":              ("infantil", "high"),
    "Roger Mas, Cobla Sant Jordi- Ciutat de Barcelona": ("folk", "high"),
    "Guillem Roma":                   ("folk",     "high"),
    "Els de la Torre":                ("folk",     "medium"),
    "Els cosins del sac":             ("folk",     "low"),
    "Al Tall, Muluk El Hwa":          ("folk",     "high"),
    "Els Xipis":                      ("infantil", "low"),
    "Miquel Gil":                     ("folk",     "high"),
    "Els Surfing Sirles":             ("rock",     "medium"),
    "Els Setze Jutges":               ("folk",     "high"),
    "Els Pets, Sopa de Cabra, Gossos, Adrià Puntí, Pep Sala, Cris Juanico, Duble Buble, Josep Thió, Gerard Quintana, Quim Mandado, Lluís Gavaldà, Montse Llaràs": ("rock", "high"),
    "Els Jóvens":                     ("indie",    "low"),
    "Illi-nois Folk Band":            ("folk",     "high"),
    "Inventari":                      ("indie",    "low"),
    "Isidor Marí":                    ("folk",     "high"),
    "Sa Cobla":                       ("folk",     "medium"),
    "Els Dracs":                      ("rock",     "low"),
    "Yung Rajola":                    ("hip-hop",  "high"),
    "Sons de mar":                    ("havaneres","high"),
    "Guillem Ramisa":                 ("indie",    "low"),
    "Els Cantaires de l'Estany":      ("havaneres","high"),
    "Sonall, música per nadons":      ("infantil", "high"),
    "Folkincats":                     ("folk",     "medium"),
    "Negre":                          ("indie",    "low"),
    "Senyor Oca":                     ("indie",    "low"),
    "31 FAM, el kid":                 ("hip-hop",  "high"),
    "roserona":                       ("indie",    "low"),
    "Estol de tramuntana":            ("folk",     "medium"),
    "Gisela":                         ("pop",      "high"),
    "Glaucs":                         ("indie",    "low"),
    "Sarau, Escola de Dances de Xàtiva": ("folk",   "high"),
    "Glòria":                         ("folk",     "low"),
    "Ocults":                         ("rock",     "high"),
    "Solé":                           ("folk",     "low"),
    "Aires formenterencs":            ("folk",     "medium"),
    "Escamarlans de Palau":           ("folk",     "low"),
    "Guillem Bautista":               ("indie",    "low"),
    "Suc i Sopes":                    ("folk",     "medium"),
    "Los Draps":                      ("folk",     "medium"),
    "Tacho":                          ("ska",      "low"),
    "Joan Colomo":                    ("indie",    "high"),
    "Joan Rovira":                    ("indie",    "medium"),
    "Joan Reverté":                   ("folk",     "low"),
    "Els Calafats":                   ("folk",     "low"),
    "Joan Ramon Bonet":               ("folk",     "medium"),
    "Ouineta":                        ("indie",    "low"),
    "Xicu":                           ("folk",     "low"),
    "El Gitano de Balaguer":          ("folk",     "medium"),
    "Orquestra de Músiques d'Arrel de Catalunya": ("folk", "high"),
    "Joan-Llorenç Solé":              ("folk",     "low"),
    "Markos":                         ("indie",    "low"),
    "Rosa Maria Sardà":               ("pop",      "high"),
    "Amansalva":                      ("folk",     "low"),
    "Javito":                         ("ska",      "low"),
    "Miguel Poveda":                  ("folk",     "high"),
    "Els 3 tambors":                  ("folk",     "low"),
    # ── Tier B — 1-song tail ──────────────────────────────────────────────
    "Vanesa Martín":                  ("pop",      "high"),
    "Pep Gimeno 'Botifarra', Xavi Sarrià, La Maria": ("folk", "high"),
    "icarians":                       ("indie",    "low"),
    "miquel":                         ("indie",    "low"),
    "POL":                            ("indie",    "low"),
    "oxigen":                         ("infantil", "medium"),
    "Uri Gheller y Los Cucharas":     ("folk",     "low"),
    "Xavier de Bétera":               ("folk",     "high"),
    "Victoria Riba, Mariona Castillo, Cor Jove de l'Orfeó Català": ("folk", "high"),
    "Vadebo":                         ("indie",    "low"),
    "Vicenç Salvador Torres Guerola": ("folk",     "low"),
    "Núria Feliu, Tete Montoliu":     ("pop",      "high"),
    "Noa":                            ("pop",      "high"),
    "Very Pomelo":                    ("indie",    "low"),
    "Xavier Piqué":                   ("folk",     "low"),
    "Pep Laguarda, Tapineria":        ("folk",     "high"),
    "Van de kul":                     ("indie",    "low"),
    "Ánimos Parrec":                  ("folk",     "low"),
    "Pep Lladó":                      ("folk",     "low"),
    "Núria Feliu, Lou Bennett":       ("pop",      "high"),
    "Vers endins":                    ("indie",    "low"),
    "Vernat":                         ("indie",    "low"),
    "Xavier Baró":                    ("folk",     "high"),
    "Àlex Pérez, Eva Sola":           ("pop",      "low"),
    "Névoa":                          ("folk",     "low"),
    "Néstor Mont":                    ("havaneres","high"),
    "Nouna":                          ("indie",    "low"),
    "Noèlia Llorens 'Titana'":        ("folk",     "high"),
    "Víctor Manuel":                  ("pop",      "high"),
    "enMatu, Maig":                   ("indie",    "low"),
    "Peret, Los Amaya, Ramonet, Chipén, Joel": ("rumba", "high"),
    "Partaka":                        ("indie",    "low"),
    "Oriol Canals":                   ("indie",    "low"),
    "Patriarcas de la Rumba":         ("rumba",    "high"),
    "Víctor, Elena Gadel":            ("pop",      "low"),
    "Oriol Tramvia":                  ("rock",     "high"),
    "Ypnosi":                         ("indie",    "low"),
    "Zona Local":                     ("indie",    "low"),
    "Will.x.o, Ceaxe, VWAE":          ("hip-hop",  "low"),
    "Orfeó Gracienc":                 ("folk",     "high"),
    "Pasquines":                      ("havaneres","medium"),
    "Víctor Bocanegra":               ("indie",    "low"),
    "Orfeó Català, K-ZU":             ("folk",     "high"),
    "Orquestra Plateria":             ("pop",      "high"),
    "Orquestra Simfònica del Gran Teatre del Liceu, India Martínez": ("pop", "high"),
    "Orchestra Fireluche":            ("rock",     "medium"),
    "Xavier Baró, Gasion":            ("folk",     "low"),
    "Yacine & The Oriental Groove":   ("folk",     "low"),
    "Paula Valls":                    ("pop",      "high"),
    "Peix Fregit, Els Pescadors de L'Escala, Port Bo, Cavall Bernat, El Taper": ("havaneres", "high"),
    "Víctor Arbelo":                  ("folk",     "low"),
    "Pascal Comelade, Enric Casasses":("indie",    "high"),
    "Oques Grasses, ZETAK":           ("indie",    "high"),
    "Partidaris":                     ("indie",    "low"),
    "Xucu-pà":                        ("infantil", "low"),
    "Xeic!":                          ("indie",    "low"),
    "Vinnie Kairos, Baya Baye MGT Los Sosis": ("hip-hop", "medium"),
    "Pellikana":                      ("indie",    "low"),
    "enMatu, AKSIS":                  ("indie",    "low"),
    "Olga Zoet":                      ("indie",    "low"),
    "Pep Gimeno 'Botifarra', Figa Flawas, Abril": ("rumba", "high"),
    "Zoo, Charly Efe, Poetas puestos": ("ska",     "high"),
    "Quinto, Abril":                  ("hip-hop",  "high"),
    "Periferia":                      ("rock",     "low"),
    "Rosmi":                          ("indie",    "low"),
    "Strombers, Altatxu":             ("ska",      "high"),
    "SDP509":                         ("indie",    "low"),
    "Ryan Paris":                     ("pop",      "high"),
    "Svetlana, Alosa":                ("folk",     "medium"),
    "Rusó Sala":                      ("folk",     "medium"),
    "Sílvia Pérez Cruz, Marco Mezquida":("folk",   "high"),
    "Sílvia Pérez Cruz, Rozalén":     ("folk",     "high"),
    "Tachita de Collblanc":           ("folk",     "low"),
    "Takul Rugi":                     ("indie",    "low"),
    "Rudy Ventura":                   ("pop",      "high"),
    "Tancat per Defunció":            ("rock",     "high"),
    "Tardor":                         ("indie",    "low"),
    "Safanòria":                      ("infantil", "low"),
    "Rosita Amores":                  ("pop",      "high"),
    "Rosalía":                        ("pop",      "high"),
    "Terra Ferma":                    ("indie",    "low"),
    "Terrae":                         ("folk",     "low"),
    "Roger Torné":                    ("indie",    "low"),
    "Roger Mas, Amaral":              ("folk",     "high"),
    "Tet i Àlex":                     ("infantil", "medium"),
    "Roger Gascon":                   ("indie",    "low"),
    "Rocky Reynaldo":                 ("rock",     "low"),
    "Rock per Xics":                  ("infantil", "high"),
    "The Mamzelles":                  ("indie",    "high"),
    "Stay Homas, Figa Flawas":        ("pop",      "high"),
    "Saltors, Saidax":                ("indie",    "low"),
    "Uri":                            ("folk",     "low"),
    "Slalom":                         ("folk",     "low"),
    "Sergio Dalma, Escolania de Montserrat": ("pop", "high"),
    "Sergio Dalma":                   ("pop",      "high"),
    "Silvestres":                     ("folk",     "low"),
    "Sergi Carbonell":                ("indie",    "low"),
    "Siroll!":                        ("infantil", "medium"),
    "Sisa, Pascal Comelade":          ("folk",     "high"),
    "Sisu":                           ("indie",    "low"),
    "Senior i el Cor Brutal":         ("rock",     "high"),
    "Selma Bruna":                    ("indie",    "low"),
    "Saó":                            ("folk",     "low"),
    "Sixtus":                         ("indie",    "low"),
    "Socunbohemio, Vittara":          ("folk",     "low"),
    "Salvatge Cor":                   ("folk",     "low"),
    "Sodi":                           ("indie",    "low"),
    "Sofia Coll":                     ("indie",    "medium"),
    "Sara Roy, Ernest Prana":         ("indie",    "low"),
    'Solistes "Oh Happy Day", Cor del Conservatori del Liceu': ("folk", "high"),
    "Santiago Auserón, Dani Nel·lo, Francesc Pareja": ("rock", "high"),
    "Som Mainada":                    ("infantil", "high"),
    "Santi Vendrell":                 ("folk",     "low"),
    "Sanjosex, Carles Belda":         ("folk",     "high"),
    "Sandra Monfort, Ferrxn":         ("indie",    "medium"),
    "Samu":                           ("indie",    "low"),
    "Samfaina de Colors":             ("infantil", "medium"),
    "River Omelet":                   ("indie",    "low"),
    "Rita Payés":                     ("folk",     "high"),
    "Rigoberta Bandini":              ("indie",    "high"),
    "Txell Sust, Toni Xuclà":         ("folk",     "high"),
    "Quartet Mèlt, Carles Arbusé":    ("folk",     "medium"),
    "Tres fan ball":                  ("folk",     "medium"),
    "Tribade":                        ("hip-hop",  "high"),
    "Quartet Mèlt":                   ("folk",     "medium"),
    "Quart primera":                  ("indie",    "low"),
    "Tro":                            ("folk",     "low"),
    "Pupil·les":                      ("indie",    "low"),
    "PulpoPop":                       ("indie",    "low"),
    "Tuna de la Facultat de Dret de Barcelona": ("folk", "high"),
    "Primera Nota":                   ("indie",    "low"),
    "Primera Cita":                   ("indie",    "low"),
    "Porto Bello":                    ("pop",      "low"),
    "Ribatònics":                     ("folk",     "low"),
    "Tànit Navarro":                  ("indie",    "low"),
    "Ual·la":                         ("indie",    "low"),
    "Pols":                           ("indie",    "low"),
    "Polnord":                        ("indie",    "low"),
    "Polifònica de Puig-Reig, Mónica Naranjo, Jove Orquestra Simfònica de Catalunya, Banda de Gaitas Xuntanza de Catalunya": ("folk", "high"),
    "Pol Bordas, Scotty DK, Figa Flawas": ("rumba", "high"),
    "Poker d'Asos":                   ("hip-hop",  "medium"),
    "Pixamandúrries":                 ("ska",      "high"),
    "Pirat's Sound Sistema":          ("ska",      "high"),
    "Univers":                        ("indie",    "low"),
    "Picot":                          ("indie",    "low"),
    "Tremendamente":                  ("havaneres","medium"),
    "Quico Pi de la Serra, Cobla Orquestra Montgrins": ("folk", "high"),
    "Quico Pi de la Serra, Maria del Mar Bonet": ("folk", "high"),
    "Quim Salvat":                    ("folk",     "low"),
    "Reïna, Plan-ET":                 ("indie",    "low"),
    "The Sucarrats Band":             ("folk",     "low"),
    "The Tyets, Dani6ix & Kashlo":    ("rumba",    "high"),
    "The Tyets, Flashy Ice Cream":    ("rumba",    "high"),
    "The Tyets, Hug Sound, Doble":    ("rumba",    "high"),
    "The Tyets, Marlena":             ("rumba",    "high"),
    "Remei Margarit":                 ("folk",     "high"),
    "The Tyets, Sexenni":             ("rumba",    "high"),
    "Rascanya":                       ("folk",     "low"),
    "The Tyets, Stay Homas":          ("rumba",    "high"),
    "Tildo Muxart":                   ("indie",    "low"),
    "Tio Fredo":                      ("folk",     "low"),
    "Ramon Casajoana, Joan Boix":     ("folk",     "high"),
    "Titelles i Cançons Pamipipa":    ("infantil", "high"),
    "Tito Pontet, Malifeta, La Raíz, Los Chikos Del Maiz, Abril": ("ska", "high"),
    "Rabadàb":                        ("infantil", "low"),
    "ROWSI":                          ("indie",    "low"),
    "RES":                            ("indie",    "low"),
    "RAWPUBLIK":                      ("indie",    "low"),
    "Tomàs de los Santos, Borja Penalba": ("folk",  "high"),
    "Toni de l'Hostal":               ("folk",     "low"),
    "Quinto, Romàntic Dimoni":        ("rock",     "medium"),
    "Tony Dallara":                   ("pop",      "high"),
    "Sense Sal":                      ("indie",    "low"),
    "080":                            ("indie",    "low"),
    "Nina, Mikel Herzog":             ("pop",      "high"),
    "El Fugitiu":                     ("indie",    "low"),
    "ESiR":                           ("indie",    "low"),
    "Eduard Gener":                   ("indie",    "low"),
    "Eina":                           ("punk",     "medium"),
    "El Belda i el Conjunt Badabadoc":("folk",     "medium"),
    "El Bonsai Blau":                 ("indie",    "low"),
    "El Cantautoret Pocatraça":       ("folk",     "medium"),
    "El Canto del Loco":              ("pop",      "high"),
    "El Fill del Mestre":             ("folk",     "low"),
    "El Grup de 3":                   ("infantil", "low"),
    "Els Amics de les Arts, The Tyets":("rumba",   "high"),
    "El Pèsol Feréstec":              ("indie",    "low"),
    "El Sac de Gemecs":               ("folk",     "high"),
    "El Triangulista":                ("indie",    "low"),
    "El Tricicle":                    ("pop",      "high"),
    "El fil d'Ariadna":               ("folk",     "low"),
    "Elena Gadel":                    ("pop",      "high"),
    "Elies":                          ("folk",     "low"),
    "Eloi Sayrach":                   ("indie",    "low"),
    "Dàmaris Gelabert, La Dona del Sac": ("infantil", "high"),
    "Duo Dinámico":                   ("pop",      "high"),
    "Dos + Un":                       ("folk",     "low"),
    "Dones de Paraula":               ("folk",     "low"),
    "Cor Infantil":                   ("infantil", "high"),
    "Cor infantil Verge de Montserrat":("infantil","high"),
    "Coral Sant Jordi, Marina Prades":("folk",     "high"),
    "Corrandes són corrandes":        ("folk",     "high"),
    "Cotó en pèl":                    ("pop",      "high"),
    "Cèlia Pallí":                    ("indie",    "low"),
    "Da Souza":                       ("indie",    "low"),
    "Dan Peralbo i El Comboi, El Comboi": ("pop",   "medium"),
    "Dani Tejedor":                   ("folk",     "low"),
    "David Torné":                    ("folk",     "low"),
    "David Uclé":                     ("indie",    "low"),
    "Davidaina":                      ("indie",    "low"),
    "De Calaix":                      ("folk",     "low"),
    "Decibelios":                     ("punk",     "high"),
    "Delfí Abella":                   ("folk",     "low"),
    "Desperta Ferro":                 ("punk",     "low"),
    "Donallop":                       ("indie",    "high"),
    "Els 4 Gats":                     ("rock",     "low"),
    "Els Berros de la Cort":          ("folk",     "low"),
    "Cookah P, Boom Boom Fighters, roots": ("ska", "medium"),
    "Funkystep & The Sey Sisters, Sara Terraza, WOM's Collective": ("pop", "medium"),
    "Figa Flawas, Mushkaa":           ("rumba",    "high"),
    "Figues d'un altre paner":        ("folk",     "low"),
    "Filibusters":                    ("punk",     "low"),
    "Filomena":                       ("infantil", "low"),
    "Font Sellabona":                 ("folk",     "low"),
    "Fortuu":                         ("indie",    "low"),
    "Frank Montasell, Lydia Torrejón":("folk",     "low"),
    "Funkystep & The Sey Sisters":    ("pop",      "medium"),
    "Fèlix Estop":                    ("folk",     "low"),
    "Els Catarres, Black Music Big Band": ("pop",   "high"),
    "Fòbia":                          ("infantil", "high"),
    "Gaietà Renom, Emili Vendrell":   ("folk",     "high"),
    "Gava y Nico":                    ("ska",      "low"),
    "Gemma Humet, Escola Superior de Música de Catalunya": ("folk", "high"),
    "George Freginald i el Col·lectiu Musicofoll": ("folk", "medium"),
    "George Freginald i el Col·lectiu Musicofoll, Peter Stampfel": ("folk", "medium"),
    "Ginestà, Laia Manzanares":       ("indie",    "high"),
    "Ginestà, Sandra Monfort, Quinto":("indie",    "high"),
    "Fenya Rai!":                     ("indie",    "low"),
    "Fauna":                          ("indie",    "low"),
    "Faneka":                         ("folk",     "medium"),
    "Família Macià":                  ("infantil", "high"),
    "Els Catarres, La Fúmiga":        ("pop",      "high"),
    "Els Cremats":                    ("rock",     "low"),
    "Els Drums":                      ("infantil", "high"),
    "Els Folls":                      ("rock",     "low"),
    "Els Vailets":                    ("infantil", "high"),
    "Emboirats":                      ("indie",    "low"),
    "Entreveus":                      ("folk",     "low"),
    "Escarteen Sisters":              ("indie",    "low"),
    "Escolania Lluc":                 ("folk",     "high"),
    "Espiral d'embulls":              ("indie",    "low"),
    "Espurnetes":                     ("infantil", "low"),
    "Estanislau Verdet":              ("folk",     "low"),
    "Estela":                         ("indie",    "low"),
    "Ester Formosa, Adolfo Osta":     ("folk",     "high"),
    "Esther, Quinto":                 ("hip-hop",  "medium"),
    "Eva Dénia":                      ("folk",     "medium"),
    "FLAKKA":                         ("rumba",    "medium"),
    "Cookah P, Raggattack":           ("ska",      "medium"),
    "Cookah P, Boom Boom Fighters":   ("ska",      "medium"),
    "Nil Moliner":                    ("pop",      "high"),
    "Andana, Boom Boom Fighters":     ("ska",      "medium"),
    "Al·lèrgiques al pol·len, gavina.mp3": ("indie", "medium"),
    "Alícia Rey, Paula Giberga":      ("indie",    "low"),
    "Amadeu Casas":                   ("folk",     "high"),
    "Amics":                          ("folk",     "low"),
    "Amygdala":                       ("hip-hop",  "low"),
    "Ana Belén":                      ("pop",      "high"),
    "Ana Torroja":                    ("pop",      "high"),
    "Andana":                         ("ska",      "medium"),
    "Andrea Motis, Joan Chamorro Group": ("pop",   "high"),
    "Arthur Caravan":                 ("indie",    "low"),
    "Angelina i els moderns":         ("indie",    "low"),
    "Anita Miltoff":                  ("indie",    "low"),
    "Antoni Parera Fons":             ("folk",     "high"),
    "Antonio Orozco, Escola de Música Centre de les Arts de l'Hospitalet de Llobregat": ("pop", "high"),
    "Antònia Font, Roba Estesa":      ("indie",    "high"),
    "Apa":                            ("folk",     "low"),
    "Aplec":                          ("folk",     "low"),
    "Arass":                          ("folk",     "low"),
    "Alquímia Musical":               ("folk",     "low"),
    "Aljub":                          ("folk",     "low"),
    "Alizzz":                         ("electronica","high"),
    "Alfred García, Álvaro Soler":    ("pop",      "high"),
    "31 FAM, Flashy Ice Cream":       ("hip-hop",  "high"),
    "4 de Copes":                     ("folk",     "low"),
    "Abelardo Ninyo Hermós":          ("folk",     "low"),
    "Acció":                          ("indie",    "low"),
    "Adala, Ayryn":                   ("ska",      "medium"),
    "Adala, Chalart58":               ("ska",      "medium"),
    "Adala, Santa Salut, Lupita's Friends": ("ska", "medium"),
    "Adala, Tribade":                 ("hip-hop",  "medium"),
    "Aigua":                          ("folk",     "low"),
    "Aina Reig":                      ("indie",    "low"),
    "Aitana":                         ("pop",      "high"),
    "Alabaix":                        ("folk",     "low"),
    "Alan Parsons":                   ("pop",      "high"),
    "Alba Carmona":                   ("folk",     "high"),
    "Albert Jordà":                   ("indie",    "low"),
    "Albert Pla, Judit Farrés":       ("folk",     "high"),
    "Albert Pla, Stay Homas":         ("folk",     "high"),
    "Ariel Santamaria":               ("folk",     "low"),
    "BAT Cheaterz":                   ("rumba",    "low"),
    "Consuelo Hueso":                 ("folk",     "low"),
    "Cati Plana, Pau Puig":           ("havaneres","medium"),
    "Calagher, aymax, Kuu, roots":    ("hip-hop",  "medium"),
    "Caliu":                          ("folk",     "low"),
    "Camerata de Cançó Tradicional":  ("folk",     "high"),
    "Camilo Sesto":                   ("pop",      "high"),
    "Caponnam":                       ("folk",     "low"),
    "Carla Collado":                  ("pop",      "low"),
    "Carles Cases":                   ("folk",     "low"),
    "Carles Cuberes":                 ("folk",     "low"),
    "Caïm Riba":                      ("indie",    "low"),
    "Bad Gyal":                       ("electronica","high"),
    "Cecília Giménez":                ("infantil", "low"),
    "Chet":                           ("folk",     "low"),
    "Christian Penalba":              ("folk",     "low"),
    "Clara, CyBee, Maria Cambray":    ("pop",      "low"),
    "Claudio Gabriel Sanna":          ("folk",     "low"),
    "Cofre Antic":                    ("folk",     "medium"),
    "Companyia Miquel Barcelona":     ("folk",     "low"),
    "Conrad Son & The Porno Band":    ("rock",     "low"),
    "Cafè d'Alguer":                  ("folk",     "medium"),
    "Cactus, Naina":                  ("indie",    "high"),
    "Cactus, NIUSS":                  ("indie",    "medium"),
    "Cabot":                          ("indie",    "low"),
    "Ballaveu":                       ("folk",     "low"),
    "Bebe":                           ("pop",      "high"),
    "Ben Trempats":                   ("folk",     "low"),
    "Bernardino i el seu Grup":       ("folk",     "low"),
    "Bikimel":                        ("folk",     "low"),
    "Black":                          ("indie",    "low"),
    "Blaumut, Suu, ZETAK":            ("indie",    "high"),
    "Blues de Picolat":               ("folk",     "low"),
    "Bohemian Betyars":               ("ska",      "low"),
    "Boom Boom Fighters":             ("ska",      "high"),
    "Boom Boom Fighters, Tropiko, El Cigarrito de Después": ("ska", "high"),
    "Boom Boom Fighters, Tropiko, Javito": ("ska", "high"),
    "Borriana Big Band":              ("pop",      "medium"),
    "Buhos, Dany BPM, Mon Dj":        ("ska",      "high"),
    "Buhos, Elena Gadel, Els Catarres, Doctor Prats": ("ska", "high"),
    "Buhos, Els Catarres":            ("ska",      "high"),
    "Buhos, En Tol Sarmiento":        ("ska",      "high"),
    "Glaucs, Menaix a Truà":          ("indie",    "low"),
    "God Save The Queen":             ("rock",     "medium"),
    "Good Jan":                       ("indie",    "low"),
    "Magalí Sare, Sebastià Gris":     ("folk",     "high"),
    "Love of Lesbian":                ("indie",    "high"),
    "Love of Lesbian, Sidonie":       ("indie",    "high"),
    "Luis Aguilé":                    ("pop",      "high"),
    "Lídia Pujol, Sílvia Comes":      ("folk",     "high"),
    "Macaco":                         ("pop",      "high"),
    "Mafalda":                        ("indie",    "low"),
    "Magalí Datzira":                 ("folk",     "high"),
    "Magalí Datzira, Kris Tena":      ("folk",     "high"),
    "Malparlat":                      ("indie",    "low"),
    "Marc Parrot, Els Catarres, Valtònyc, Guillem Roma, Oques Grasses, Judit Neddermann, Roba Estesa, Lildami, Suu, Pavvla, Núria Graham": ("pop", "high"),
    "Mama Dousha, Gigi Ros":          ("hip-hop",  "high"),
    "Mama Dousha, Scotty DK":         ("hip-hop",  "high"),
    "Manel, P.A.W.N. Gang":           ("indie",    "high"),
    "Manolo Escobar":                 ("pop",      "high"),
    "Manu Guix, Elena Gadel, La Simfònica de Corda i Cobla de Catalunya": ("pop", "high"),
    "Manuel Carrasco":                ("pop",      "high"),
    "Maps":                           ("indie",    "low"),
    "Mar Pujol, Henrio":              ("folk",     "medium"),
    "Los Sirgadors":                  ("folk",     "low"),
    "Los Javaloyas":                  ("pop",      "high"),
    "Los Beta Quartet":               ("infantil", "low"),
    "Los 5 del Este":                 ("folk",     "low"),
    "Les Putes Van a Peu":            ("punk",     "low"),
    "Les anxovetes":                  ("havaneres","high"),
    "Lia Kali":                       ("pop",      "high"),
    "Libérica":                       ("folk",     "low"),
    "Lildami, Sr. Chen":              ("hip-hop",  "high"),
    "Llacuna":                        ("indie",    "low"),
    "Llicsons":                       ("indie",    "low"),
    "Lluciana Sari":                  ("folk",     "low"),
    "Lluís Gavaldà":                  ("rock",     "high"),
    "Lluís Gavaldà, Figa Flawas":     ("rumba",    "high"),
    "Lluís Llach, Estrella Morente":  ("folk",     "high"),
    "Lluís Llach, Feliu Ventura":     ("folk",     "high"),
    "Lluís Llach, Montse Castellà":   ("folk",     "high"),
    "Lluís Llach, Teresa Rebull":     ("folk",     "high"),
    "Lluís Sánchez":                  ("indie",    "low"),
    "Lo Pardal Roquer":               ("folk",     "low"),
    "Lorena":                         ("pop",      "low"),
    "Marc Egea":                      ("folk",     "low"),
    "Marcel Lázara i Júlia Arrey":    ("indie",    "low"),
    "Grans amb pus":                  ("rock",     "low"),
    "Mosaic":                         ("pop",      "low"),
    "Miquel Cors":                    ("folk",     "low"),
    "Miquel Fernández, Gabriela Richardson": ("pop", "low"),
    "Miquel Gil, Orquestra Àrab de Barcelona": ("folk", "high"),
    "Miquel del Roig":                ("folk",     "low"),
    "Miquela Lladó":                  ("folk",     "medium"),
    "Mirna":                          ("indie",    "low"),
    "Monegre":                        ("folk",     "low"),
    "Montserrat Caballé, Montserrat Martí": ("pop", "high"),
    "Mosaic, Alex Cortés":            ("pop",      "low"),
    "Margarett":                      ("pop",      "low"),
    "Mushkaa, Bexnil":                ("pop",      "high"),
    "Mushkaa, roots":                 ("pop",      "high"),
    "Musicants":                      ("havaneres","medium"),
    "N'Gai N'Gai":                    ("indie",    "low"),
    "Naakhum":                        ("rock",     "low"),
    "Nastallat":                      ("folk",     "low"),
    "Natural":                        ("indie",    "low"),
    "Nia":                            ("pop",      "high"),
    "Miki Núñez, Sexenni":            ("pop",      "high"),
    "Miki Núñez, Mon Dj":             ("pop",      "high"),
    "Miguel Bosé, Virgínia Martínez, Orfeó Català": ("pop", "high"),
    "Meteor":                         ("indie",    "low"),
    "Maria Amèlia Pedrerol":          ("folk",     "low"),
    "Maria Antònia Pujol, Xavier Guitó": ("folk",  "low"),
    "Maria Castell Margenat":         ("folk",     "low"),
    "Maria Dolors Cruells":           ("folk",     "low"),
    "Maria Helena Tolosa":            ("folk",     "low"),
    "Maria del Carme Bustamante":     ("folk",     "low"),
    "Maria del Mar Bonet, Manel Camp":("folk",     "high"),
    "Maria Àngels Gornés":            ("folk",     "low"),
    "Marina BBface & The Beatroots":  ("indie",    "low"),
    "Marina Villegas":                ("indie",    "low"),
    "Mariona Escoda, Ernest Prana":   ("indie",    "medium"),
    "Marremango":                     ("infantil", "low"),
    "Mary Santpere":                  ("pop",      "high"),
    "Mascarats":                      ("folk",     "low"),
    "Max Navarro":                    ("indie",    "low"),
    "Mercè Madolell":                 ("folk",     "low"),
    "Mercè Torrents, Maria Laffitte": ("folk",     "high"),
    "Les Absentes":                   ("indie",    "low"),
    "Le Croupier":                    ("indie",    "low"),
    "Laura Gibert":                   ("indie",    "low"),
    "Jordan's Trio":                  ("folk",     "low"),
    "Joan Manuel Serrat, Joaquín Sabina": ("folk", "high"),
    "Joan Martorell":                 ("folk",     "low"),
    "Joan Masdéu, Salva Racero, Funambulista, Andrés Suárez": ("pop", "high"),
    "Joan Rafart":                    ("folk",     "low"),
    "Joanjo Bosk, L'Orquestra de Cambra de L'Empordà": ("folk", "high"),
    "Joaquín Sabina":                 ("folk",     "high"),
    "Joni Txintxes":                  ("indie",    "low"),
    "Jorcx":                          ("indie",    "low"),
    "Jordan's Trio, Coral Xaloc":     ("folk",     "low"),
    "Lal’Ba":                         ("indie",    "low"),
    "Jordi Bardella":                 ("folk",     "low"),
    "Jordi Vidal":                    ("folk",     "low"),
    "Josmar":                         ("indie",    "low"),
    "Ju":                             ("indie",    "low"),
    "Ju, David Busquets":             ("indie",    "low"),
    "Juan Valderrama":                ("pop",      "high"),
    "JudJou":                         ("indie",    "low"),
    "Judit Neddermann, Alessio Arena, Sara Pi": ("folk", "high"),
    "Joan Garriga i el Mariatxi galàctic, Carles Belda": ("ska", "high"),
    "Joan Dausà, Paula Koops":        ("pop",      "high"),
    "Joan Adrià Pistola":             ("infantil", "low"),
    "Jimmy Fontana":                  ("pop",      "high"),
    "Grup Bergantí":                  ("folk",     "low"),
    "Guillem Roma, Mar Pujol":        ("folk",     "high"),
    "Guillermina Motta, Marina Rossell, Miquel Cors, Coral Sant Jordi, Lluís Saumell": ("folk", "high"),
    "HHH":                            ("indie",    "low"),
    "Habla de mí en presente, Alosa": ("indie",    "medium"),
    "Herbes Dolces":                  ("folk",     "low"),
    "Herois de la Katalunya Interior":("ska",      "low"),
    "Hey Zuri":                       ("indie",    "low"),
    "Hilari Alonso":                  ("folk",     "low"),
    "Huapachà Combo":                 ("ska",      "medium"),
    "Hugo Mas":                       ("indie",    "low"),
    "Hèctor Vila":                    ("indie",    "low"),
    "Icestorm":                       ("indie",    "low"),
    "Ivette Nadal":                   ("folk",     "high"),
    "Jarabe de Palo":                 ("pop",      "high"),
    "Jaume Arnella, Rafel Sala":      ("folk",     "high"),
    "JazzWoman":                      ("hip-hop",  "high"),
    "Judit Neddermann, Meritxell Neddermann": ("folk", "high"),
    "Julieta, Mushkaa":               ("pop",      "high"),
    "Julieta, Mushkaa, roots":        ("pop",      "high"),
    "La Fúmiga, Samantha":            ("pop",      "high"),
    "La Guardiola Groga":             ("infantil", "low"),
    "La Oreja de Van Gogh":           ("pop",      "high"),
    "La Pegatina, Els Amics de les Arts": ("ska",  "high"),
    "La Principal de la Bisbal, The Gospel Viu Choir, Raphael": ("folk", "high"),
    "La Puça":                        ("folk",     "low"),
    "La Ratonera":                    ("infantil", "low"),
    "La Rauxa":                       ("indie",    "low"),
    "La Romàntica del Saladar":       ("folk",     "low"),
    "La Rondalla de la Costa":        ("folk",     "low"),
    "La Salseta del Poble Sec":       ("ska",      "high"),
    "La Taverna":                     ("folk",     "low"),
    "La Terrasseta de Preixens":      ("ska",      "medium"),
    "La Tour de Carol":               ("indie",    "low"),
    "La Tribu canta":                 ("infantil", "low"),
    "La Trocamba Matanusca":          ("folk",     "low"),
    "La Viu-viu":                     ("folk",     "low"),
    "La cuca viu":                    ("infantil", "low"),
    "La Fúmiga, The Tyets":           ("pop",      "high"),
    "La Fúmiga, Naina":               ("pop",      "high"),
    "Júlia Bobb":                     ("indie",    "low"),
    "La Fúmiga, Esther, Àlex Blat":   ("pop",      "high"),
    "Júlia Boncompte":                ("indie",    "low"),
    "K-ZU":                           ("indie",    "low"),
    "KYNE, Javier Bayon, Luc Suárez": ("hip-hop",  "low"),
    "Kepa Junkera":                   ("folk",     "high"),
    "Km.0, Les que Faltaband":        ("indie",    "low"),
    "Koers":                          ("indie",    "low"),
    "Koers, Bemba Saoco, Suu, Herzog, The Soul Beams, Chipper": ("pop", "low"),
    "Kris Tena":                      ("indie",    "low"),
    "L'Ham de Foc":                   ("folk",     "high"),
    "L'Équilibriste":                 ("indie",    "low"),
    "La Baula":                       ("folk",     "low"),
    "La Belluga":                     ("infantil", "low"),
    "La Carrau, Josep Thió, Manu Guix, Tomeu Penya, Abús, Ivette Nadal, Pastora, Love of Lesbian, Sidonie, Shuarma, Lolita, Chenoa, Arianna Puello, Flavio Rodríguez, Manolo Escobar, Abdeljalil Kodssi": ("pop", "high"),
    "La Colla Pirata":                ("infantil", "medium"),
    "La Companyia MINIMíssimA":       ("infantil", "low"),
    "La Criatura Verda":              ("infantil", "low"),
    "La Fúmiga, Abril":               ("pop",      "high"),
    "Òscar Briz":                     ("folk",     "high"),
}


def main(check_only: bool = False) -> None:
    if not _TOP_5000_CSV.exists():
        raise FileNotFoundError(
            f"Top-5000 CSV not found at {_TOP_5000_CSV}. "
            "Run `python -m etl.build_top_songs` first."
        )

    top = pd.read_csv(_TOP_5000_CSV, encoding="utf-8-sig", skipinitialspace=True)
    top.columns = [c.strip().lstrip("#").strip() for c in top.columns]
    top["artist"] = top["artist"].astype(str).str.strip()
    artists_in_csv = {a for a in top["artist"].unique() if a and a.lower() != "nan"}
    labeled = set(ARTIST_GENRES.keys())

    missing = artists_in_csv - labeled
    extra   = labeled - artists_in_csv
    if missing:
        sample = sorted(missing)[:20]
        raise ValueError(
            f"{len(missing)} artists missing from ARTIST_GENRES. "
            f"First 20: {sample}"
        )
    if extra:
        sample = sorted(extra)[:20]
        raise ValueError(
            f"{len(extra)} extra artists in ARTIST_GENRES (not in top-5000). "
            f"First 20: {sample}"
        )

    bad = {a: g for a, (g, _) in ARTIST_GENRES.items() if g not in GENRES}
    if bad:
        raise ValueError(f"Unknown genres assigned: {bad}")

    if check_only:
        logger.info("Coverage OK: %d artists, all in taxonomy.", len(ARTIST_GENRES))
        return

    rows = [
        {"artist": a, "genre": g, "confidence": c}
        for a, (g, c) in ARTIST_GENRES.items()
    ]
    df = pd.DataFrame(rows).sort_values("artist", kind="stable")
    _OUTPUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(_OUTPUT_CSV, index=False, quoting=csv.QUOTE_MINIMAL)

    logger.info("Wrote %d rows to %s", len(df), _OUTPUT_CSV)
    logger.info("Genre distribution:\n%s",
                df["genre"].value_counts().to_string())
    logger.info("Confidence distribution:\n%s",
                df["confidence"].value_counts().to_string())


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    p = argparse.ArgumentParser(description="Build artist_genres.csv from curated labels.")
    p.add_argument("--check", action="store_true",
                   help="Validate coverage without writing the CSV.")
    args = p.parse_args()
    main(check_only=args.check)
